spring:
  datasource:
    url: jdbc:mysql://localhost:3306/90s?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: root
    dbcp2:
      validation-query: SELECT 1
